# Generated by Django 4.2.7 on 2023-12-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
