# Generated by Django 5.0 on 2023-12-18 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subarticle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.category'),
        ),
        migrations.AlterField(
            model_name='subnews',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BD.category'),
        ),
    ]
